// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'dart:developer' as developer;

import 'package:flutter/foundation.dart';
import 'package:logging/logging.dart';

/// The app's logging. Install it once, from `bootstrap()`.
///
/// Every message and error passes through [redact] before it is emitted, so a
/// token or an Authorization header logged by mistake never reaches the
/// console or, later, a crash reporter.
class AppLogger {
  const AppLogger._();

  static final Logger root = Logger('Notes');

  static bool _installed = false;

  static void install({Level level = kReleaseMode ? Level.INFO : Level.ALL}) {
    if (_installed) return;
    _installed = true;
    Logger.root.level = level;
    Logger.root.onRecord.listen((record) {
      developer.log(
        redact(record.message),
        name: record.loggerName,
        level: record.level.value,
        time: record.time,
        error: record.error == null ? null : redact(record.error.toString()),
        stackTrace: record.stackTrace,
      );
    });
  }

  /// Bearer tokens, `token=…` pairs and anything that looks like a JWT.
  static String redact(String value) => value
      .replaceAll(
        RegExp(r'Bearer\s+[A-Za-z0-9._~+/-]+=*', caseSensitive: false),
        'Bearer [redacted]',
      )
      .replaceAllMapped(
        RegExp(
          r'(token|password|secret|api[_-]?key|authorization)(\s*[:=]\s*"?)([^\s"&,}]+)',
          caseSensitive: false,
        ),
        (match) => '${match[1]}${match[2]}[redacted]',
      )
      .replaceAll(
        RegExp(r'\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+'),
        '[redacted-jwt]',
      );

  @visibleForTesting
  static void resetForTest() => _installed = false;
}
