// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:notes/app/app.dart';
import 'package:notes/app/router/home_screen.dart';
import 'package:notes/core/storage/preferences_store.dart';

import 'helpers/pump_app.dart';

void main() {
  testWidgets('the app starts and renders its first route', (tester) async {
    SharedPreferences.setMockInitialValues(<String, Object>{});
    final preferences = await PreferencesStore.open();

    await pumpApp(
      tester,
      const NotesApp(),
      overrides: [preferencesStoreProvider.overrideWithValue(preferences)],
    );

    expect(find.byType(MaterialApp), findsOneWidget);
    expect(find.byType(HomeScreen), findsOneWidget);
  });
}
