// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:notes/app/theme/theme_mode_controller.dart';

/// What the settings screen shows and can change.
///
/// The screen reads this and nothing else, so a new setting is added here and
/// in the screen's list — never by reaching into another module's provider.
class SettingsState {
  const SettingsState({
    required this.themeMode,
    required this.availableThemeModes,
  });

  final ThemeMode themeMode;
  final List<ThemeMode> availableThemeModes;
}

class SettingsController extends Notifier<SettingsState> {
  @override
  SettingsState build() {
    return SettingsState(
      themeMode: ref.watch(themeModeControllerProvider),
      availableThemeModes: supportedThemeModes,
    );
  }

  Future<void> setThemeMode(ThemeMode mode) =>
      ref.read(themeModeControllerProvider.notifier).set(mode);
}

final settingsControllerProvider =
    NotifierProvider<SettingsController, SettingsState>(SettingsController.new);
