// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
// Walks the screens that go into the store listing and names each shot.
// Names become <NN>_<name>.png: NN is the position in the store set (01-10).
import 'dart:io' show Platform;

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:notes/app/app.dart';
import 'package:notes/app/router/app_router.dart';
import 'package:notes/app/router/routes.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('store screenshots', (tester) async {
    final container = ProviderContainer();
    addTearDown(container.dispose);
    final router = container.read(appRouterProvider);
    const app = NotesApp();

    await tester.pumpWidget(
      UncontrolledProviderScope(container: container, child: app),
    );
    await tester.pumpAndSettle();

    // Android renders into a texture that cannot be read back until the surface
    // becomes an image view. iOS does not need this conversion.
    if (Platform.isAndroid) {
      await binding.convertFlutterSurfaceToImage();
      await tester.pumpAndSettle();
    }

    await binding.takeScreenshot('01_home');

    router.go(AppRoutes.settings);
    await tester.pumpAndSettle();
    await binding.takeScreenshot('02_settings');
  });
}
