// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Preferences: locale, theme mode, onboarding state.
///
/// Never secrets. SharedPreferences is plain storage on both platforms; a
/// token or a password belongs in secure storage.
class PreferencesStore {
  const PreferencesStore(this._preferences);

  final SharedPreferences _preferences;

  static Future<PreferencesStore> open() async =>
      PreferencesStore(await SharedPreferences.getInstance());

  String? getString(String key) => _preferences.getString(key);
  bool? getBool(String key) => _preferences.getBool(key);
  int? getInt(String key) => _preferences.getInt(key);

  Future<void> setString(String key, String value) =>
      _preferences.setString(key, value);
  Future<void> setBool(String key, {required bool value}) =>
      _preferences.setBool(key, value);
  Future<void> setInt(String key, int value) => _preferences.setInt(key, value);
  Future<void> remove(String key) => _preferences.remove(key);
}

/// Overridden in `bootstrap()` with the opened store.
final preferencesStoreProvider = Provider<PreferencesStore>(
  (ref) => throw UnimplementedError(
    'preferencesStoreProvider must be overridden in bootstrap()',
  ),
);
