// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.

import 'dart:async';
import 'dart:io';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter_reactive_ble/flutter_reactive_ble.dart';
import 'package:permission_handler/permission_handler.dart';

/// Performs a bounded foreground BLE scan. No location-derived scan mode is
/// used.
class BleScanService {
  BleScanService({FlutterReactiveBle? ble}) : _injectedBle = ble;

  final FlutterReactiveBle? _injectedBle;
  FlutterReactiveBle? _createdBle;

  /// Created on the first scan, never earlier: constructing the plugin starts
  /// the Bluetooth stack, which on iOS shows the permission prompt and in
  /// widget tests has no platform implementation. Cancelling or leaving a
  /// screen that never scanned must not touch it.
  FlutterReactiveBle get _ble =>
      _injectedBle ?? (_createdBle ??= FlutterReactiveBle());
  StreamSubscription<DiscoveredDevice>? _activeSubscription;
  Timer? _scanTimer;
  Completer<List<String>>? _scanResult;
  final Map<String, DiscoveredDevice> _found = <String, DiscoveredDevice>{};

  Future<List<String>> scan({
    Duration timeout = const Duration(seconds: 6),
  }) async {
    if (_scanResult != null) throw StateError('A BLE scan is already running.');
    _found.clear();
    final completed = Completer<List<String>>();
    _scanResult = completed;
    try {
      if (!await _requestPermissions()) {
        throw StateError('Bluetooth scan permission was denied.');
      }
      // cancel() may run while Android shows the permission prompt. In that
      // case, never start discovery after the screen leaves the foreground.
      if (completed.isCompleted) return await completed.future;
      _scanTimer = Timer(timeout, () {
        if (!completed.isCompleted) completed.complete(_labels(_found.values));
      });
      _activeSubscription = _ble
          .scanForDevices(
            withServices: const <Uuid>[],
            scanMode: ScanMode.lowLatency,
            requireLocationServicesEnabled: false,
          )
          .listen(
            (device) => _found[device.id] = device,
            onError: (Object error, StackTrace stack) {
              if (!completed.isCompleted) completed.completeError(error, stack);
            },
            onDone: () {
              if (!completed.isCompleted) {
                completed.complete(_labels(_found.values));
              }
            },
          );
      return await completed.future;
    } finally {
      _scanTimer?.cancel();
      _scanTimer = null;
      await _activeSubscription?.cancel();
      _activeSubscription = null;
      _scanResult = null;
    }
  }

  Future<bool> _requestPermissions() async {
    if (!Platform.isAndroid) return true;
    final android = await DeviceInfoPlugin().androidInfo;
    final permissions = android.version.sdkInt >= 31
        ? <Permission>[Permission.bluetoothScan, Permission.bluetoothConnect]
        : <Permission>[Permission.locationWhenInUse];
    final results = await permissions.request();
    return results.values.every(
      (status) => status.isGranted || status.isLimited,
    );
  }

  Future<void> cancel() async {
    _scanTimer?.cancel();
    await _activeSubscription?.cancel();
    final result = _scanResult;
    if (result != null && !result.isCompleted) {
      result.complete(_labels(_found.values));
    }
  }

  List<String> _labels(Iterable<DiscoveredDevice> devices) =>
      devices
          .map((device) {
            final name = device.name.trim();
            final label = name.isEmpty ? 'Unnamed device' : name;
            return '$label · ${device.id} · RSSI ${device.rssi} dBm';
          })
          .toList(growable: false)
        ..sort();
}
