// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:notes/l10n/app_localizations.dart';
import 'package:notes/screen_gen.dart';

import 'router/app_router.dart';
import 'theme/app_theme.dart';
import 'theme/theme_mode_controller.dart';

/// The root widget. Everything it needs is read from providers, so a test can
/// replace any of them without touching this class.
class NotesApp extends ConsumerWidget {
  const NotesApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    final themeMode = ref.watch(themeModeControllerProvider);

    return MaterialApp.router(
      title: 'Notes',
      debugShowCheckedModeBanner: false,
      routerConfig: router,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      // Null in every ordinary run, so the app follows the device; set only
      // while Screen Gen is capturing one locale at a time.
      locale: screenGenLocale(),
    );
  }
}
