// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/misc.dart' show Override;
import 'package:notes/core/logging/app_logger.dart';
import 'package:notes/core/storage/preferences_store.dart';
import 'package:notes/services/media/media_picker_service.dart';

import 'app.dart';

/// Builds the overrides the app starts with and runs it.
Future<void> bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();
  await MediaPickerService.instance.initialize();
  AppLogger.install();

  final overrides = <Override>[
    preferencesStoreProvider.overrideWithValue(await PreferencesStore.open()),
  ];

  FlutterError.onError = (details) {
    AppLogger.root.severe(
      'Uncaught Flutter error',
      details.exception,
      details.stack,
    );
    FlutterError.presentError(details);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    AppLogger.root.severe('Uncaught error', error, stack);
    return true;
  };

  runApp(ProviderScope(overrides: overrides, child: const NotesApp()));
}
