// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:notes/core/storage/preferences_store.dart';

/// The theme modes this app offers, in the order a settings screen lists them.
const List<ThemeMode> supportedThemeModes = <ThemeMode>[
  ThemeMode.light,
  ThemeMode.dark,
  ThemeMode.system,
];

/// The current theme mode.
///
/// Read from preferences at start-up and written back on every change.
class ThemeModeController extends Notifier<ThemeMode> {
  static const _key = 'theme_mode';

  @override
  ThemeMode build() {
    final stored = ref.watch(preferencesStoreProvider).getString(_key);
    return supportedThemeModes.firstWhere(
      (mode) => mode.name == stored,
      orElse: () => supportedThemeModes.first,
    );
  }

  Future<void> set(ThemeMode mode) async {
    if (!supportedThemeModes.contains(mode) || mode == state) return;
    state = mode;
    await ref.read(preferencesStoreProvider).setString(_key, mode.name);
  }
}

final themeModeControllerProvider =
    NotifierProvider<ThemeModeController, ThemeMode>(ThemeModeController.new);
