// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_test/flutter_test.dart';
import 'package:notes/core/errors/app_failure.dart';

void main() {
  group('AppFailure', () {
    test('network and server failures are worth retrying', () {
      expect(const AppFailure.network().isRetryable, isTrue);
      expect(
        const AppFailure(
          kind: AppFailureKind.server,
          message: 'Server error',
          statusCode: 500,
        ).isRetryable,
        isTrue,
      );
    });

    test('a refused credential is not retried by the caller', () {
      const failure = AppFailure(
        kind: AppFailureKind.unauthorized,
        message: 'Session expired',
        statusCode: 401,
      );

      expect(failure.isRetryable, isFalse);
      expect(failure.toString(), contains('HTTP 401'));
    });

    test('validation failures carry the fields that were refused', () {
      const failure = AppFailure(
        kind: AppFailureKind.validation,
        message: 'Check the form',
        fieldErrors: {'email': 'Enter a valid email address'},
      );

      expect(failure.fieldErrors['email'], isNotNull);
    });
  });
}
