// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:notes/features/settings/presentation/screens/settings_screen.dart';
import 'package:notes/app/design/app_design.dart';

import 'home_screen.dart';
import 'not_found_screen.dart';
import 'routes.dart';

/// The router, built once per app.
///
/// It is a provider rather than a global so a test can override it, and so the
/// guards it will grow later have somewhere to read state from.
final appRouterProvider = Provider<GoRouter>((ref) {
  return GoRouter(
    initialLocation: AppRoutes.home,
    debugLogDiagnostics: false,
    routes: <RouteBase>[
      GoRoute(
        path: AppRoutes.home,
        builder: (context, state) => const HomeScreen(),
      ),
      GoRoute(
        path: '/screens/profile',
        builder: (context, state) => const AppDesignScreen(screenIndex: 1),
      ),
      GoRoute(
        path: '/screens/settings',
        builder: (context, state) => const AppDesignScreen(screenIndex: 2),
      ),
      GoRoute(
        path: AppRoutes.settings,
        builder: (context, state) => const SettingsScreen(),
      ),
    ],
    errorBuilder: (context, state) =>
        NotFoundScreen(location: state.uri.toString()),
  );
});
