// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:notes/app/design/app_design.dart';

/// The first editable screen declared by the AppGen design editor.
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) => const AppDesignScreen(screenIndex: 0);
}
