// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'routes.dart';

/// What an address the app does not have looks like.
class NotFoundScreen extends StatelessWidget {
  const NotFoundScreen({required this.location, super.key});

  /// The address that was asked for. Shown so a bad link is reportable.
  final String location;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Page not found')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text(location, style: Theme.of(context).textTheme.bodySmall),
              const SizedBox(height: 16),
              FilledButton(
                onPressed: () => context.go(AppRoutes.home),
                child: const Text('Go back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
