// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
/// Every address in the app, in one place.
///
/// Screens navigate with these constants and never with a string literal, so
/// renaming a path is one edit and the compiler finds the rest.
class AppRoutes {
  const AppRoutes._();

  static const String home = '/';
  static const String settings = '/settings';
}
