// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
/// What went wrong, in terms the UI can act on.
enum AppFailureKind {
  /// No usable connection, or the request never reached the server.
  network,

  /// The server answered, and the answer was an error.
  server,

  /// The credential is missing, expired or refused.
  unauthorized,

  /// The request was understood and refused.
  forbidden,

  /// What was asked for does not exist.
  notFound,

  /// The input was rejected; `fieldErrors` says which fields.
  validation,

  /// Reading or writing local storage failed.
  storage,

  /// Anything not classified above.
  unknown,
}

/// A failure the app can show and decide about.
///
/// [message] is safe to display. [cause] and [stackTrace] are for the log and
/// never for a screen.
class AppFailure implements Exception {
  const AppFailure({
    required this.kind,
    required this.message,
    this.statusCode,
    this.fieldErrors = const {},
    this.cause,
    this.stackTrace,
  });

  const AppFailure.network([
    this.message = 'No connection. Check your network and try again.',
  ]) : kind = AppFailureKind.network,
       statusCode = null,
       fieldErrors = const {},
       cause = null,
       stackTrace = null;

  const AppFailure.unknown([this.message = 'Something went wrong.'])
    : kind = AppFailureKind.unknown,
      statusCode = null,
      fieldErrors = const {},
      cause = null,
      stackTrace = null;

  final AppFailureKind kind;
  final String message;
  final int? statusCode;
  final Map<String, String> fieldErrors;
  final Object? cause;
  final StackTrace? stackTrace;

  /// Whether trying the same thing again could plausibly work.
  bool get isRetryable =>
      kind == AppFailureKind.network || kind == AppFailureKind.server;

  @override
  String toString() =>
      'AppFailure(${kind.name}, $message${statusCode == null ? '' : ', HTTP $statusCode'})';
}
