// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'app_environment.dart';

/// Everything the app needs to know about where it is running.
///
/// Values come from `--dart-define`, with the committed defaults below as the
/// development fallback. No secret is ever a default: see `.env.example`.
class AppConfig {
  const AppConfig({required this.environment, required this.appName});

  factory AppConfig.resolve() {
    final environment = AppEnvironment.current;
    return AppConfig(environment: environment, appName: 'Notes');
  }

  final AppEnvironment environment;
  final String appName;

  bool get isProduction => environment.isProduction;
}
