// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
/// Which deployment the running app is talking to.
///
/// Chosen at build time with `--dart-define=APP_ENV=staging`, never at run
/// time: a build is for one environment, and that is auditable.
enum AppEnvironment {
  development,
  staging,
  production;

  static const _fromDefine = String.fromEnvironment(
    'APP_ENV',
    defaultValue: 'development',
  );

  static AppEnvironment get current => AppEnvironment.values.firstWhere(
    (value) => value.name == _fromDefine,
    orElse: () => AppEnvironment.development,
  );

  bool get isProduction => this == AppEnvironment.production;
}
