// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.

import 'dart:typed_data';

import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Opens the operating system photo picker and returns the selected image bytes.
/// Cancellation returns null; callers can handle platform errors at the UI edge.
class MediaPickerService {
  MediaPickerService._({ImagePicker? imagePicker})
    : _imagePicker = imagePicker ?? ImagePicker();

  static final MediaPickerService instance = MediaPickerService._();
  static const int maxPhotoBytes = 10 * 1024 * 1024;

  final ImagePicker _imagePicker;
  static const _pendingActionKey = 'appgen.pendingMediaAction';
  bool _pickerOpen = false;
  Future<MapEntry<String, Uint8List>?>? _recovery;

  Future<void> initialize() async {
    try {
      await recoverLostPhoto();
    } catch (_) {
      // An invalid recovery result must not prevent the app from starting.
    }
  }

  Future<Uint8List?> pickPhoto({required String actionId}) =>
      _pick(actionId, ImageSource.gallery);

  Future<Uint8List?> capturePhoto({required String actionId}) =>
      _pick(actionId, ImageSource.camera);

  Future<Uint8List?> _pick(String actionId, ImageSource source) async {
    if (_pickerOpen) throw StateError('A photo picker is already open.');
    _pickerOpen = true;
    try {
      final preferences = await SharedPreferences.getInstance();
      await preferences.setString(_pendingActionKey, actionId);
      final image = await _imagePicker.pickImage(
        source: source,
        requestFullMetadata: false,
        maxWidth: 4096,
        maxHeight: 4096,
        imageQuality: 85,
      );
      if (image == null) return null;
      final length = await image.length();
      if (length > maxPhotoBytes) {
        throw const FormatException('Selected photo exceeds the 10 MB limit.');
      }
      return await image.readAsBytes();
    } finally {
      // If Android kills the activity, this finally block does not run. The
      // next app launch can then associate retrieveLostData() with this action.
      try {
        final preferences = await SharedPreferences.getInstance();
        await preferences.remove(_pendingActionKey);
      } finally {
        _pickerOpen = false;
      }
    }
  }

  /// Kept by this app-scoped singleton so navigation cannot discard recovery.
  Future<MapEntry<String, Uint8List>?> recoverLostPhoto() =>
      _recovery ??= _recoverLostPhoto();

  Future<MapEntry<String, Uint8List>?> _recoverLostPhoto() async {
    final preferences = await SharedPreferences.getInstance();
    final actionId = preferences.getString(_pendingActionKey);
    if (actionId == null) return null;
    try {
      final response = await _imagePicker.retrieveLostData();
      final files = response.files;
      if (response.isEmpty || files == null || files.isEmpty) return null;
      final file = files.first;
      if (await file.length() > maxPhotoBytes) {
        throw const FormatException('Recovered photo exceeds the 10 MB limit.');
      }
      return MapEntry(actionId, await file.readAsBytes());
    } finally {
      await preferences.remove(_pendingActionKey);
    }
  }
}
