// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:notes/app/router/app_router.dart';
import 'package:notes/app/router/home_screen.dart';
import 'package:notes/app/router/routes.dart';

void main() {
  ProviderContainer containerFor() {
    final container = ProviderContainer();
    addTearDown(container.dispose);
    return container;
  }

  Future<GoRouter> pumpRouter(
    WidgetTester tester,
    ProviderContainer container,
  ) async {
    final router = container.read(appRouterProvider);
    await tester.pumpWidget(
      UncontrolledProviderScope(
        container: container,
        child: MaterialApp.router(routerConfig: router),
      ),
    );
    await tester.pumpAndSettle();
    return router;
  }

  group('appRouterProvider', () {
    testWidgets('starts at the home route', (tester) async {
      await pumpRouter(tester, containerFor());

      expect(find.byType(HomeScreen), findsOneWidget);
    });

    testWidgets('an unknown address lands on the not-found screen', (
      tester,
    ) async {
      final router = await pumpRouter(tester, containerFor());

      router.go('/does-not-exist');
      await tester.pumpAndSettle();

      expect(find.text('Page not found'), findsOneWidget);

      router.go(AppRoutes.home);
      await tester.pumpAndSettle();
    });
  });
}
