// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_test/flutter_test.dart';
import 'package:notes/core/logging/app_logger.dart';

void main() {
  group('AppLogger.redact', () {
    test('removes a bearer token', () {
      expect(
        AppLogger.redact('GET /me failed: Bearer abc.def-ghi'),
        'GET /me failed: Bearer [redacted]',
      );
    });

    test('removes a JWT wherever it appears', () {
      final line = AppLogger.redact(
        'session eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3OCJ9.SflKxwRJSMeKKF2QT4fwpM expired',
      );

      expect(line, contains('[redacted-jwt]'));
      expect(line, isNot(contains('SflKxwRJSMeKKF2QT4fwpM')));
    });

    test('removes the value of a named secret', () {
      expect(AppLogger.redact('?api_key=super-secret'), '?api_key=[redacted]');
    });

    test('leaves an ordinary message alone', () {
      expect(AppLogger.redact('Loaded 12 items'), 'Loaded 12 items');
    });
  });
}
