// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/misc.dart' show Override;
import 'package:flutter_test/flutter_test.dart';

/// Pumps [widget] inside the scope a real screen runs in.
///
/// [overrides] replaces providers a test wants to control; everything else
/// behaves exactly as it does in the app.
Future<void> pumpApp(
  WidgetTester tester,
  Widget widget, {
  List<Override> overrides = const [],
}) async {
  await tester.pumpWidget(ProviderScope(overrides: overrides, child: widget));
  await tester.pumpAndSettle();
}

/// The same, for a widget that is not itself an app.
Future<void> pumpScreen(
  WidgetTester tester,
  Widget screen, {
  List<Override> overrides = const [],
}) => pumpApp(tester, MaterialApp(home: screen), overrides: overrides);
