// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../controllers/settings_controller.dart';

/// The settings screen. Every row reads and writes through
/// [settingsControllerProvider].
class SettingsScreen extends ConsumerWidget {
  const SettingsScreen({super.key});

  static const Map<ThemeMode, String> _themeModeLabels = <ThemeMode, String>{
    ThemeMode.light: 'Light',
    ThemeMode.dark: 'Dark',
    ThemeMode.system: 'Match the system',
  };

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(settingsControllerProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: ListView(
        children: <Widget>[
          const Padding(
            padding: EdgeInsets.fromLTRB(16, 24, 16, 8),
            child: Text('Appearance'),
          ),
          for (final mode in settings.availableThemeModes)
            ListTile(
              title: Text(_themeModeLabels[mode] ?? mode.name),
              trailing: mode == settings.themeMode
                  ? const Icon(Icons.check)
                  : null,
              selected: mode == settings.themeMode,
              onTap: () => ref
                  .read(settingsControllerProvider.notifier)
                  .setThemeMode(mode),
            ),
        ],
      ),
    );
  }
}
