// Generated by AppGen v1. Edit freely: AppGen never writes to this repository again.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:notes/core/config/app_config.dart';

/// The resolved configuration of this build.
///
/// Providers that need `await` are declared by the module that owns them and
/// overridden in `bootstrap()`; this file holds the ones every app has.
final appConfigProvider = Provider<AppConfig>((ref) => AppConfig.resolve());
